CREATE TABLE IF NOT EXISTS bng.england_010k_4326
(
	ogc_fid UUID CONSTRAINT pk_england_010k_4326_ogc_fid PRIMARY KEY DEFAULT uuid_generate_v4(),
  objectid INTEGER NOT NULL,
  identifier INTEGER NOT NULL,
  long_name CHARACTER VARYING(50) NOT NULL,
  short_name CHARACTER VARYING(30) NOT NULL,
  code CHARACTER VARYING(3) NOT NULL,
  descriptio CHARACTER VARYING(250) NOT NULL,
  seaward CHARACTER VARYING(3) NOT NULL,
  date_from TIMESTAMP WITH TIME ZONE NOT NULL,
  date_to TIMESTAMP WITH TIME ZONE NOT NULL,
  shape_leng DOUBLE PRECISION NOT NULL,
  shape_length DOUBLE PRECISION NOT NULL,
  shape_area DOUBLE PRECISION NOT NULL,
  geometry GEOMETRY(MultiPolygon, 4326) NOT NULL
);
