##############################################################################################################
# Common project docker build options.
# This builds the docker images for azure
##############################################################################################################
services:
  ##############################################################################################################
  # Biodiversity net gain service application to register webapp
  ##############################################################################################################
  application-to-register-webapp:
    image: ${CONTAINER_REGISTRY}/application-to-register-webapp:${TAG:-latest}
    build:
      context: ../
      dockerfile: packages/application-to-register-webapp/dockerfile
