version: "3.9"
secrets:
  WEBAPP_ENV:
    file: ./secrets/WEBAPP_ENV
services:
  ##############################################################################################################
  # Biodiversity net gain service - Application to register webapp - web app found on localhost:3000
  ##############################################################################################################
  webapp:
    image: bng/application-to-register-webapp:${TAG:-latest}
    ports:
      - "3000:3000"
    secrets:
      - WEBAPP_ENV
    entrypoint: [ '/bin/sh', '-c', "source /run/secrets/WEBAPP_ENV && npm run start" ]
