##############################################################################################################
# Common project docker build options.
# This builds the docker images
##############################################################################################################
services:
##############################################################################################################
  # Custom image for Azure services
  #
  # Azure Functions Core Tools on port 8072
  # Azure SignalR emulator on port 8888
  ##############################################################################################################
  azure_services:
    build:
      context: ..
      dockerfile: docker/azure-services/Dockerfile
    ports:
      - "8082:7071"
      - "8888:8888"
  ##############################################################################################################
  # Biodiversity net gain service application to register webapp
  ##############################################################################################################
  application-to-register-webapp:
    image: bng/application-to-register-webapp:${TAG:-latest}
    build:
      context: ../packages/application-to-register-webapp
      dockerfile: ${PROJECT_DOCKERFILE:-dockerfile}
