version: "3.9"
services:
  ##############################################################################################################
  # Biodiversity net gain service - Application to register webapp - web app found on localhost:3000
  ##############################################################################################################
  webapp:
    image: biodiversity-net-gain-service/application-to-register-webapp:${TAG:-latest}
    ports:
      - "3000:3000"
    env_file:
      - ./env/webapp.env
      - ./env/webapp.secrets.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure