##############################################################################################################
# Common project docker build options.
# This builds the docker images for azure
##############################################################################################################
services:
  ##############################################################################################################
  # Biodiversity net gain service application to register webapp
  ##############################################################################################################
  webapp:
    image: ${CONTAINER_REGISTRY}/webapp:${TAG:-latest}
    build:
      context: ../
      dockerfile: packages/webapp/dockerfile
