##############################################################################################################
# Common project docker build options.
# This builds the docker images
##############################################################################################################
services:
  ##############################################################################################################
  # Biodiversity net gain service application to register webapp
  ##############################################################################################################
  webapp:
    image: bng/webapp:${TAG:-latest}
    build:
      context: ../
      args:
        - GOOGLE_TAGMANAGER_ID
      dockerfile: packages/webapp/dockerfile
