##############################################################################################################
# Common project docker build options.
# This builds the docker images for azure
##############################################################################################################
services:
  ##############################################################################################################
  # Biodiversity net gain service application to register webapp
  ##############################################################################################################
  application-to-register-webapp:
    image: bngcr.azurecr.io/application-to-register-webapp:latest
    build:
      context: ../packages/application-to-register-webapp
      dockerfile: dockerfile.azure
