#######
# This docker file is for deployment to azure infrastructure flavour
#######
version: "3.9"
services:
  ##############################################################################################################
  # Biodiversity net gain service - Application to register webapp
  ##############################################################################################################
  webapp:
    image: ${CONTAINER_REGISTRY}.azurecr.io/application-to-register-webapp:latest
    container_name: webapp
    ports:
      - "80:80"
    env_file:
      - ./secrets/WEBAPP_REMOTE
 