DO $$
BEGIN
  IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_CATALOG = 'bng' AND TABLE_SCHEMA = 'bng' AND TABLE_NAME = 'england_010k_4326') THEN
    TRUNCATE TABLE bng.england_010k_4326;
  END IF;
END
$$

