#######
# This docker file is for deployment to azure infrastructure flavour
#######
version: "3.9"
secrets:
  SESSION_COOKIE_PASSWORD:
    file: ../../docker/secrets/SESSION_COOKIE_PASSWORD
  POSTGRES_PASSWORD:
    file: ../../docker/secrets/POSTGRES_PASSWORD
services:
    ##############################################################################################################
  # Redis - on port 6379
  ##############################################################################################################
  redis:
    image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    container_name: redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"
    # volumes:
    #   - ${WEBAPP_STORAGE_HOME}/volumes/redis:/data
    deploy:
      restart_policy:
        condition: on-failure

  ##############################################################################################################
  # Biodiversity net gain service - Application to register webapp - web app found on localhost:3000
  ##############################################################################################################
  webapp:
    image: bnglocaldev.azurecr.io/application-to-register-webapp:latest
    ports:
      - "80:80"
    # environment:
    #   - SESSION_COOKIE_PASSWORD=/run/secrets/SESSION_COOKIE_PASSWORD
    # secrets:
    #   - SESSION_COOKIE_PASSWORD
    env_file:
      - ../../docker/env/webapp.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
